name = "pdf-analyzer"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
API_KEY = "sk-kswoezfgvjelkqbocvcpuezvpcmksjpkcrrlfgdlspqgktwl"
BASE_URL = "https://api.siliconflow.cn/v1"
MODEL = "Qwen/Qwen2.5-7B-Instruct"
